config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
     controllers: { sessions: 'user/sessions' }

  devise_scope :user do
    authenticated :user do
      # 認証済みユーザーの場合はファイル一覧へ
      root to: 'folders#show'
    end
    unauthenticated :user do
      root to: 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  # folder_idはどのフォルダ一覧へ戻るかを示すためのキー。省略可能。省略時はrootへ戻る事になる
  get 'find(/:folder_id)' => 'find#new', as: 'find', defaults: {folder_id: nil}
  post 'find(/:folder_id)' => 'find#show', as: 'find_result', defaults: {folder_id: nil}

  resources :folders, only: [:show] do
    member do
      # /folders/3/search | /search/3
      get :search
    end
    resources :upfiles, only: [:edit, :create, :new, :destroy, :update, :show] do
      member do
        get :download
        post :move, :copy
        resource :fileshare, only: [:new, :update, :destroy]
        namespace 'toshare' do
          get :show, to: 'upfiles#show'
          get :download, to: 'upfiles#download'
        end
      end
    end

    resources :folders, controller: :subfolders, only: [:edit, :create, :new, :destroy, :update, :show] do
      member do
        post :move, :copy
        resource :foldershare, only: [:new, :update, :destroy]
        namespace 'toshare' do
          get :show, to: 'subfolders#show'
        end
      end
    end
  end

  namespace 'fromshare' do
    resources :items, only: [:index]
  end

  namespace 'toshare' do
    resources :items, only: [:index]
    resources :folders, only: [:show]
  end

  resources :events, only: [:index]
end

app/models/upfile.rb
class Upfile < ActiveRecord::Base
  belongs_to :folder
  belongs_to :own_user, class_name: :User, foreign_key: :user_id
  has_many :file_shares, inverse_of: :upfile, dependent: :destroy
  accepts_nested_attributes_for :file_shares, allow_destroy: true
  has_many :from_share_users, through: :file_shares, source: :from_user
  has_many :to_share_users, through: :file_shares, source: :to_user

  validate :my_folder
  validates :name, presence: true,
    length: {maximum: 100}
  validates :user_id, presence: true
  validates :folder_id, presence: true

  after_create  -> {
    add_event(Const.event_type.create, self.user_id)
  }
  after_update  -> {
    add_event(Const.event_type.update, self.user_id)
  }
  after_destroy -> {
    add_event(Const.event_type.destroy, self.user_id)
  }

  def move(moveto_folder_id)
    if self.folder_id.to_s == moveto_folder_id
      errors.add(:folder_id, "同じフォルダへは移動できません。")
      return false
    end
    self.transaction do
      self.folder_id = moveto_folder_id
      self.save!
      add_event(Const.event_type.move, self.user_id)
    end
    true
  rescue => e
    errors.add(:folder_id, "移動できませんでした。#{e.message}")
    false
  end

  def copy(copyto_folder_id)
    self.transaction do
      copyfile = self.dup
      copyfile.folder_id = copyto_folder_id
      copyfile.save!
      add_event(Const.event_type.copy, self.user_id)
    end
    true
  rescue => e
    errors.add(:folder_id, "コピーできませんでした。#{e.message}")
    false
  end

  def deliver_shared_email
    self.file_shares.each do |item|
      NoticeMailer.sendmail_share(self, item.to_user).deliver
    end
  end

  def add_event(event_type, user_id)
    Event.create(upfile_id: self.id,
                 upfile_name: self.name,
                 event_type: event_type,
                 user_id: user_id
                 )
  end

  attr_accessor :current_user

  private
    def my_folder
      errors.add(:folder_id, '不正なフォルダです') unless User.find(self.user_id).folders.pluck(:id).include?(self.folder_id)
    end
end

app/controllers/toshare/upfiles_controller.rb
class Toshare::UpfilesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_upfile, only: [:show, :download]

  def show
  end

  def download
    send_data(@upfile.file_binary, filename: @upfile.name)
    @upfile.add_event(Const.event_type.download, current_user.id)
  end

  private
    def set_upfile
      @upfile = current_user.to_share_files_all.find(params[:id])
    end

end

app/controllers/upfiles_controller.rb
class UpfilesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_folder
  before_action :set_upfiles, only: [:new, :create]
  before_action :set_upfile, only: [:show, :edit, :update, :destroy, :download, :move, :copy]

  def show
  end

  def edit
  end

  def new
    @upfile = @upfiles.build
  end

  def move
    respond_to do |format|
      if @upfile.move(upfile_movecopy_params)
        format.html { redirect_to folder_path(upfile_movecopy_params), notice: '移動しました' }
      else
        format.html { redirect_to folder_path(@folder.id), notice: @upfile.errors.messages[:folder_id].join }
      end
    end
  end

  def copy
    respond_to do |format|
      if @upfile.copy(upfile_movecopy_params)
        format.html { redirect_to folder_path(upfile_movecopy_params), notice: 'コピーしました' }
      else
        format.html { redirect_to folder_path(@folder.id), notice: @upfile.errors.messages[:folder_id].join }
      end
    end
  end

  def download
    send_data(@upfile.file_binary, filename: @upfile.name)
    @upfile.add_event(Const.event_type.download, current_user.id)
  end

  def create
    upload_file = upfile_params.blank? ? nil : upfile_params[:upload_file]
    rec_values  = {}
    if upload_file.present?
      rec_values[:file_binary] = upload_file.read
      rec_values[:name]        = upload_file.original_filename
    end
    rec_values[:user_id] = current_user.id

    @upfile = @upfiles.build(rec_values)
    respond_to do |format|
      if @upfile.save
        format.html { redirect_to folder_path(@folder), notice: 'ファイルをアップロードしました' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @upfile.update(upfile_edit_params)
        format.html { redirect_to folder_upfile_path(@folder, @upfile), notice: '更新しました' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @upfile.destroy
    respond_to do |format|
      format.html { redirect_to folder_path(@folder), notice: 'ファイルを削除しました' }
    end
  end

  private
  def set_folder
    @folder = current_user.folders.find(params[:folder_id])
  end

  def set_upfiles
    @upfiles = @folder.upfiles
  end

  def set_upfile
    @upfile = @folder.upfiles.find(params[:id])
  end

  def upfile_params
    params.fetch(:upfile, {}).permit(:upload_file)
  end

  def upfile_edit_params
    params.require(:upfile).permit(:name)
  end

  def upfile_movecopy_params
    params.require(:to_folder_id)
  end
end

app/views/upfiles/_editform.html.haml
= form_for ([@folder, @upfile]) do |f|
  - if @upfile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@upfile.errors.count, "error")} prohibited this upfile from being saved:"
      %ul
        - @upfile.errors.full_messages.each do |msg|
          %li= msg

  = f.text_field :name

  .actions
    = f.submit '保存'

app/views/upfiles/_form.html.haml
= form_for ([@folder, @upfile]) do |f|
  - if @upfile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@upfile.errors.count, "error")} prohibited this upfile from being saved:"
      %ul
        - @upfile.errors.full_messages.each do |msg|
          %li= msg

  = f.text_field :name

  .actions
    = f.submit '保存'

app/views/upfiles/_moveform.html.haml
= form_for ([@folder, @upfile]),{url: move_folder_upfile_path(@folder, @upfile)}  do |f|
  #current
    = f.label :現在のフォルダ：
    = link_to @folder.name, search_folder_path(@folder), {id: 'current_folder',class: 'search_folder',remote: true}

  #moveto_folder

  %hr

  #tree

  = hidden_field_tag :authenticity_token, form_authenticity_token

  %hr
  .actions
    = f.submit '移動する'

app/views/upfiles/_uploadform.html.haml
= form_for ([@folder, @upfile]) do |f|
  - if @upfile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@upfile.errors.count, "error")} prohibited this upfile from being saved:"
      %ul
        - @upfile.errors.full_messages.each do |msg|
          %li= msg

  = f.file_field :upload_file
  ※Heroku環境では大きなサイズのファイルはアップロードできません

  .actions
    = f.submit 'アップロード'

app/views/upfiles/edit.html.haml
%h1 ファイル名変更

= render 'form'

%hr
= link_to '参照', folder_upfile_path(@folder, @upfile)
\|
=link_to '戻る', :back

app/views/upfiles/new.html.haml
%h1 ファイルアップロード

アップロード先フォルダ： #{@folder.name}

%hr

= render 'uploadform'

= link_to '一覧へ', folder_path(@folder)

app/views/upfiles/show.html.haml
%p
  %strong ファイル名:
  = @upfile.name
%p
  %strong サイズ:
  = "#{@upfile.file_binary.length}バイト"
%p
  %strong 更新日時:
  = get_disp_update_time(@upfile)
%p
  %strong 所有者:
  = @upfile.own_user.email
%p
  %strong 共有相手:
  = @upfile.to_share_users.pluck(:email).uniq.join(', ')

%hr

= link_to 'ダウンロード', download_folder_upfile_path(@folder, @upfile), 'data-no-turbolink' => true
\|
= link_to '編集', edit_folder_upfile_path(@folder, @upfile)
\|
= link_to '移動', '', id: "show_movetree"
\|
= link_to 'コピー', '', id: "show_copytree"
\|
= link_to '一覧へ', folder_path(@folder)



#movetreedialog
  = render 'folders/searchform', { param: { title: '移動', form_for: [@folder, @upfile], url: move_folder_upfile_path(@folder, @upfile) } }

#copytreedialog
  = render 'folders/searchform', { param: { title: 'コピー', form_for: [@folder, @upfile], url: copy_folder_upfile_path(@folder, @upfile) } }