config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
     controllers: { sessions: 'user/sessions' }

  devise_scope :user do
    authenticated :user do
      # 認証済みユーザーの場合はファイル一覧へ
      root to: 'folders#show'
    end
    unauthenticated :user do
      root to: 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  # folder_idはどのフォルダ一覧へ戻るかを示すためのキー。省略可能。省略時はrootへ戻る事になる
  get 'find(/:folder_id)' => 'find#new', as: 'find', defaults: {folder_id: nil}
  post 'find(/:folder_id)' => 'find#show', as: 'find_result', defaults: {folder_id: nil}

  resources :folders, only: [:show] do
    member do
      # /folders/3/search | /search/3
      get :search
    end
    resources :upfiles, only: [:edit, :create, :new, :destroy, :update, :show] do
      member do
        get :download
        post :move, :copy
        resource :fileshare, only: [:new, :update, :destroy]
        namespace 'toshare' do
          get :show, to: 'upfiles#show'
          get :download, to: 'upfiles#download'
        end
      end
    end

    resources :folders, controller: :subfolders, only: [:edit, :create, :new, :destroy, :update, :show] do
      member do
        post :move, :copy
        resource :foldershare, only: [:new, :update, :destroy]
        namespace 'toshare' do
          get :show, to: 'subfolders#show'
        end
      end
    end
  end

  namespace 'fromshare' do
    resources :items, only: [:index]
  end

  namespace 'toshare' do
    resources :items, only: [:index]
    resources :folders, only: [:show]
  end

  resources :events, only: [:index]
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  has_many :upfiles, dependent: :destroy
  belongs_to :own_user, class_name: :User, foreign_key: :user_id
  has_many :folder_shares, inverse_of: :folder, :dependent => :destroy
  accepts_nested_attributes_for :folder_shares, allow_destroy: true
  has_many :from_share_users, through: :folder_shares, source: :from_user
  has_many :to_share_users, through: :folder_shares, source: :to_user

  has_many :sub_folders, class_name: :Folder, foreign_key: :parent_folder_id , dependent: :destroy
  belongs_to :parent_folder, class_name: :Folder, foreign_key: :parent_folder_id

  scope :root_folder, -> { find_by(parent_folder_id: nil) }
  scope :get_folder_or_root, ->(folder_id){
    folder_id.blank? ? root_folder : find_by(id: folder_id) || root_folder
  }

  validate :my_parent_folder
  validates :name, presence: true,
    length: {maximum: 100}
  validates :user_id, presence: true

  after_create  -> {
    add_event(Const.event_type.create, self.user_id)
  }
  after_update  -> {
    add_event(Const.event_type.update, self.user_id)
  }
  after_destroy -> {
    add_event(Const.event_type.destroy, self.user_id)
  }

  def get_family_folders
    families = {}
    families[:parent] = { id: self.parent_folder.id, name:self.parent_folder.name } unless self.parent_folder_id.blank?
    families[:self]   = { id: self.id, name: self.name }
    if self.sub_folders.present?
      childs = []
      self.sub_folders.each do |sub_folder|
        childs << { id: sub_folder.id, name: sub_folder.name }
      end
      families[:child] = childs
    end
    families
  end

  # 親を辿ってparents配列にセットする
  def all_parents(parents)
    parents << self
    parent = self.parent_folder
    parent.all_parents(parents) if parent.present?
  end

  # フォルダを中身を含めて移動する
  def deepmove(moveto_folder_id)
    if self.id.to_s == moveto_folder_id
      errors.add(:parent_folder_id, "同じフォルダへは移動できません。")
      return false
    end
    subfolders = self.get_subfolders([])
    self.transaction do
      if subfolders.include?(moveto_folder_id.to_i)
        # 自分のサブフォルダ内に移動する場合は、親子関係が崩れるので
        # 崩れないようにつなぎ直す
        self.sub_folders.each do |sub_folder|
          sub_folder.parent_folder_id = self.parent_folder_id
          sub_folder.save!
        end
      end
      self.parent_folder_id = moveto_folder_id
      self.save!
      add_event(Const.event_type.move, self.user_id)
    end
    true
  rescue => e
    errors.add(:parent_folder_id, "移動できませんでした。#{e.message}")
    false
  end

  def get_subfolders(subfolders)
    if self.sub_folders.present?
      self.sub_folders.each do |sub_folder|
        subfolders << sub_folder.id
        sub_folder.get_subfolders(subfolders)
      end
    end
    subfolders
  end

  # フォルダを中身を含めてコピーする
  def deepcopy(copyto_folder_id)
    if self.id.to_s == copyto_folder_id
      errors.add(:parent_folder_id, "同じフォルダへはコピーできません。")
      return false
    end
    self.transaction do
      self.id == copyto_folder_id
      copyfolder = self.dup
      copyfolder.parent_folder_id = copyto_folder_id
      copyfolder.save!
      add_event(Const.event_type.copy, self.user_id)
      self.copyall(copyfolder)
    end
    true
  rescue => e
    errors.add(:parent_folder_id, "コピーできませんでした。#{e.message}")
    false
  end

  def copyall(copyto_folder)
    self.upfiles.each do |upfile|
      copyfile = upfile.dup
      copyfile.folder_id = copyto_folder.id
      copyfile.save!
      upfile.add_event(Const.event_type.copy, upfile.user_id)
    end
    self.sub_folders.each do |subfolder|
      copyfolder = subfolder.dup
      copyfolder.parent_folder_id = copyto_folder.id
      copyfolder.save!
      add_event(Const.event_type.copy, subfolder.user_id)
      subfolder.copyall(copyfolder)
    end

  end

  def deliver_shared_email
    self.folder_shares.each do |item|
      NoticeMailer.sendmail_share(self, item.to_user).deliver
    end
  end

  def add_event(event_type, user_id)
    Event.create(folder_id: self.id,
                 folder_name: self.name,
                 event_type: event_type,
                 user_id: user_id
                 )
  end

  attr_accessor :current_user

  private
    def my_parent_folder
      return if self.parent_folder_id.blank?

      errors.add(:parent_folder_id, '不正な親フォルダです') unless User.find(self.user_id).folders.pluck(:id).include?(self.parent_folder_id)
    end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  include ItemsOrderby
  before_filter :authenticate_user!
  before_action :set_orderby, only: [:show]
  before_action :set_folder

  def show
  end

  def search
   @search_result =  @folder.get_family_folders
  end

  private
    def set_folder
      @folder = current_user.folders.get_folder_or_root(params[:id])
    end

end

app/controllers/toshare/folders_controller.rb
class Toshare::FoldersController < ApplicationController
  include ItemsOrderby
  before_filter :authenticate_user!
  before_action :set_orderby, only: [:show]
  before_action :set_folder

  def show
  end

  private
    def set_folder
      @folder = current_user.to_share_folders.find(params[:id])
    end

end

app/helpers/folders_helper.rb
module FoldersHelper
  def file_link_tag(target_object)
    if target_object.kind_of?(Folder)
      return link_to target_object.name, list_folder_path(target_object)
    end

    if target_object.kind_of?(Upfile)
      return link_to target_object.name, folder_upfile_path(target_object.folder_id, target_object)
    end
  end

  def toshare_file_link_tag(target_object)
    if target_object.kind_of?(Folder)
      return link_to target_object.name, toshare_list_folder_path(target_object)
    end

    if target_object.kind_of?(Upfile)
     # return link_to target_object.name, toshare_folder_upfile_path(target_object.folder_id, target_object)
    end
  end

  def file_view_tag(target_object)
    if target_object.kind_of?(Folder)
      return link_to '詳細', folder_folder_path(target_object.parent_folder_id, target_object)
    end

    if target_object.kind_of?(Upfile)
      return link_to '詳細', folder_upfile_path(target_object.folder_id, target_object)
    end
  end

  def file_edit_tag(target_object)
    if target_object.kind_of?(Folder)
      return link_to '編集', edit_folder_folder_path(target_object.parent_folder_id, target_object)
    end

    if target_object.kind_of?(Upfile)
      return link_to '編集', edit_folder_upfile_path(target_object.folder_id, target_object)
    end
  end

  def share_link_tag(target_object)
    if target_object.kind_of?(Folder)
      return link_to '共有', newshares_folder_folder_path(target_object.parent_folder_id, target_object)
    end

    if target_object.kind_of?(Upfile)
      return link_to '共有', newshares_folder_upfile_path(target_object.folder_id, target_object)
    end
  end

  def destroy_share_link_tag(target_object)
    if target_object.kind_of?(Folder)
      return link_to '共有解除',destroyshares_folder_folder_path(target_object.parent_folder_id, target_object) , :method => :delete, :data => { :confirm => '共有解除してもよろしいですか？' }
    end

    if target_object.kind_of?(Upfile)
      return link_to '共有解除',destroyshares_folder_upfile_path(target_object.folder_id, target_object) , :method => :delete, :data => { :confirm => '共有解除してもよろしいですか？' }
    end
  end

  def sharelist_header_tag(field, orderby, link_path)
    field_name = get_list_header_title(field)
    now_orderby, next_orderby, arrow =
      get_list_header_orderby(field, orderby)

    field_name << arrow

    link_to field_name, "#{link_path}?f=#{field}&o=#{next_orderby}"
  end

  def filelist_header_tag(field, folder, orderby)
    field_name = get_list_header_title(field)
    now_orderby, next_orderby, arrow =
      get_list_header_orderby(field, orderby)

    field_name << arrow

    link_to field_name, list_folder_path(folder,
      f: field,
      o: next_orderby,
    )
  end

  def get_list_header_title(field)
    case field
      when Const.orderby.field.file
        'ファイル'
      when Const.orderby.field.type
        '種別'
      when Const.orderby.field.time
        '更新'
      when Const.orderby.field.owner
        '所有者'
    end
  end

  def get_list_header_orderby(field, orderby)
    orderby_item, orderby_value = get_orderby_params(orderby)
    now_orderby = orderby_value
    next_orderby = Const.orderby.asce
    arrow = ''
    if field == orderby_item
      case now_orderby
        when Const.orderby.asce
          next_orderby = Const.orderby.desc
          arrow = '↓'
        when Const.orderby.desc
          next_orderby = Const.orderby.asce
          arrow = '↑'
      end
    end
    # p "---> #{field_name} #{orderby_item} #{orderby_value} "
    return now_orderby, next_orderby, arrow
  end

  def get_orderby_params(orderby)
    orderby_item  = Const.orderby.field.file
    orderby_value = Const.orderby.none
    orderby.each do |key, value|
      if value != Const.orderby.none
        orderby_item  = key
        orderby_value = value
      end
    end
    return orderby_item,orderby_value.to_i
  end

  def get_toshare_list_folder_source(folder, orderby)
    items = []
    add_items_toshare_folder_upfiles(items, folder)
    items_orderby(items, orderby)
    items
  end

  def get_toshare_items(orderby)
    items = []
    add_items_toshare_folders(items)
    add_items_toshare_upfiles(items)
    items_orderby(items, orderby)
    items.uniq!
    items
  end

  def add_items_toshare_folders(items)
    # 共有されたフォルダを抽出
    current_user.to_share_folders.each do |f|
      rec = {
        Const.orderby.field.file => f.name,
        Const.orderby.field.type => get_disp_type_name(f),
        Const.orderby.field.time => get_disp_update_time(f),
        Const.orderby.field.owner => get_disp_own_user_name(f),
        object: f
      }
      items << rec
    end
  end

  def add_items_toshare_upfiles(items)
    # 共有されたファイルを抽出
    current_user.to_share_files.each do |f|
      rec = {
        Const.orderby.field.file => f.name,
        Const.orderby.field.type => get_disp_type_name(f),
        Const.orderby.field.time => get_disp_update_time(f),
        Const.orderby.field.owner => get_disp_own_user_name(f),
        object: f
      }
      items << rec
    end
  end

  def get_fromshare_items(orderby)
    items = []
    add_items_fromshare_folders(items)
    add_items_fromshare_upfiles(items)
    items_orderby(items, orderby)
    items.uniq!
    items
  end

  def add_items_fromshare_folders(items)
    # 共有したフォルダを抽出
    current_user.from_share_folders.each do |f|
      rec = {
        Const.orderby.field.file => f.name,
        Const.orderby.field.type => get_disp_type_name(f),
        Const.orderby.field.time => get_disp_update_time(f),
        object: f
      }
      items << rec
    end
  end

  def add_items_fromshare_upfiles(items)
    # 共有したファイルを抽出
    current_user.from_share_files.each do |f|
      rec = {
        Const.orderby.field.file => f.name,
        Const.orderby.field.type => get_disp_type_name(f),
        Const.orderby.field.time => get_disp_update_time(f),
        object: f
      }
      items << rec
    end
  end

  def get_folder_items(folder, orderby)
    items = []
    add_items_sub_folders(items, folder)
    add_items_upfiles(items, folder)
    items_orderby(items, orderby)
    items
  end

  def add_items_sub_folders(items, folder)
    # サブフォルダを抽出
    folder.sub_folders.each do |f|
      rec = {
        Const.orderby.field.file => f.name,
        Const.orderby.field.type => get_disp_type_name(f),
        Const.orderby.field.time => get_disp_update_time(f),
        object: f
      }
      items << rec
    end
  end

  def add_items_upfiles(items, folder)
    # フォルダ内のファイルを抽出
    folder.upfiles.each do |f|
      rec = {
        Const.orderby.field.file => f.name,
        Const.orderby.field.type => get_disp_type_name(f),
        Const.orderby.field.time => get_disp_update_time(f),
        object: f
      }
      items << rec
    end
  end

  def items_orderby(items, orderby)
    orderby_item, orderby_value = get_orderby_params(orderby)
    if orderby_value != Const.orderby.none
      items.sort_by! { |item| item[orderby_item] }
      items.reverse! if orderby_value == Const.orderby.desc
    end
  end
end

app/views/folders/_search_result.html.haml
= family_folders_html(@search_result)

app/views/folders/_search_result_selected.html.haml
= family_folders_selected_html(@search_result)

app/views/folders/_searchform.html.haml
= form_for ("#{param[:form_for]}"),{url: "#{param[:url]}"} do |f|
  #current
    = f.label :現在のフォルダ：
    = link_to @folder.name, search_folder_path(@folder), {id: 'current_folder',class: 'search_folder',remote: true}

  %div.to_folder

  %hr

  %div.tree

  = hidden_field_tag :authenticity_token, form_authenticity_token

  %hr
  .actions
    = f.submit "#{param[:title]}する"

app/views/folders/_treeform.html.haml
= form_for ([@folder, @upfile]),{url: move_folder_upfile_path(@folder, @upfile)}  do |f|
  #current
    = f.label :現在のフォルダ：
    = link_to @folder.name, search_folder_path(@folder), {id: 'current_folder',class: 'search_folder',remote: true}

  #moveto_folder

  %hr

  #tree

  = hidden_field_tag :authenticity_token, form_authenticity_token

  %hr
  .actions
    = f.submit '移動する'

app/views/folders/index.html.haml
%h1 フォルダ  #{folder_parents_html(@folder)}

%hr

- if @folder.errors.any?
  #error_explanation
    %h2= "#{pluralize(@folder.errors.count, "error")} prohibited this upfile from being saved:"
    %ul
      - @folder.errors.full_messages.each do |msg|
        %li= msg
%table
  %tr
    %th= filelist_header_tag(Const.orderby.field.file, @folder, @orderby)
    %th= filelist_header_tag(Const.orderby.field.type, @folder, @orderby)
    %th= filelist_header_tag(Const.orderby.field.time, @folder, @orderby)

  - folder_items = get_folder_items(@folder, @orderby)
  - folder_items.each do |i|
    %tr
      %td= file_link_tag(i[:object])
      %td= get_disp_type_name(i[:object])
      %td= get_disp_update_time(i[:object])
      %td= file_view_tag(i[:object])
      %td= file_edit_tag(i[:object])
      %td= share_link_tag(i[:object])
      %td= link_to '削除', [@folder, i[:object]], :method => :delete, :data => { :confirm => '削除してもよろしいですか？' }

%hr

= link_to 'アップロード', new_folder_upfile_path(@folder)
\|
= link_to 'フォルダ作成', new_folder_folder_path(@folder)
- if @folder.parent_folder.present?
  \|
  = link_to 'フォルダ名編集', edit_folder_folder_path(@folder.parent_folder, @folder)
\|
= link_to 'ファイル検索', find_path(@folder)

app/views/folders/show.html.haml
%h1 フォルダ  #{folder_parents_html(@folder)}

%hr

- if @folder.errors.any?
  #error_explanation
    %h2= "#{pluralize(@folder.errors.count, "error")} prohibited this upfile from being saved:"
    %ul
      - @folder.errors.full_messages.each do |msg|
        %li= msg
%table
  %tr
    %th= items_header_tag(Const.orderby.field.file, @folder, @orderby)
    %th= items_header_tag(Const.orderby.field.type, @folder, @orderby)
    %th= items_header_tag(Const.orderby.field.time, @folder, @orderby)

  - folder_items = get_folder_items(@folder, @orderby)
  - folder_items.each do |i|
    %tr
      %td= item_link_tag(i[:object])
      %td= get_disp_type_name(i[:object])
      %td= get_disp_update_time(i[:object])
      %td= item_view_tag(i[:object])
      %td= item_edit_tag(i[:object])
      %td= share_link_tag(i[:object])
      %td= link_to '削除', [@folder, i[:object]], :method => :delete, :data => { :confirm => '削除してもよろしいですか？' }

%hr

= link_to 'アップロード', new_folder_upfile_path(@folder)
\|
= link_to 'フォルダ作成', new_folder_folder_path(@folder)
- if @folder.parent_folder.present?
  \|
  = link_to 'フォルダ名編集', edit_folder_folder_path(@folder.parent_folder, @folder)
\|
= link_to 'ファイル検索', find_path(@folder)