config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
     controllers: { sessions: 'user/sessions' }

  devise_scope :user do
    authenticated :user do
      # 認証済みユーザーの場合はファイル一覧へ
      root to: 'folders#show'
    end
    unauthenticated :user do
      root to: 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  # folder_idはどのフォルダ一覧へ戻るかを示すためのキー。省略可能。省略時はrootへ戻る事になる
  get 'find(/:folder_id)' => 'find#new', as: 'find', defaults: {folder_id: nil}
  post 'find(/:folder_id)' => 'find#show', as: 'find_result', defaults: {folder_id: nil}

  resources :folders, only: [:show] do
    member do
      # /folders/3/search | /search/3
      get :search
    end
    resources :upfiles, only: [:edit, :create, :new, :destroy, :update, :show] do
      member do
        get :download
        post :move, :copy
        resource :fileshare, only: [:new, :update, :destroy]
        namespace 'toshare' do
          get :show, to: 'upfiles#show'
          get :download, to: 'upfiles#download'
        end
      end
    end

    resources :folders, controller: :subfolders, only: [:edit, :create, :new, :destroy, :update, :show] do
      member do
        post :move, :copy
        resource :foldershare, only: [:new, :update, :destroy]
        namespace 'toshare' do
          get :show, to: 'subfolders#show'
        end
      end
    end
  end

  namespace 'fromshare' do
    resources :items, only: [:index]
  end

  namespace 'toshare' do
    resources :items, only: [:index]
    resources :folders, only: [:show]
  end

  resources :events, only: [:index]
end

app/controllers/find_controller.rb
class FindController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_folder

  def new
  end

  def show
    @input_name = find_params
    @upfiles = current_user.upfiles.where('name like ?',  "%#{@input_name}%").order(:name)
    flash.now[:notice] = "検索結果：#{@upfiles.count}件"
    render action: :new
  end

  private
    def set_folder
      @folder = current_user.folders.get_folder_or_root(params[:folder_id])
    end
    def find_params
      params.fetch(:name,'')
    end


end

app/views/find/new.html.haml
%h1 ファイル検索

%hr
= form_tag(find_result_path(@folder), { method: :post }) do

  = label_tag :ファイル名
  = text_field_tag :name, @input_name

  %br

  .actions
    = submit_tag '検索'

- if @upfiles.present?
  %hr
  %table
    %tr
      %th フォルダ
      %th ファイル
      %th 種類
      %th 更新

    - @upfiles.each do |upfile|
      %tr
        %td= item_link_tag(upfile.folder)
        %td= item_link_tag(upfile)
        %td= get_disp_type_name(upfile)
        %td= get_disp_update_time(upfile)

%hr

= link_to '一覧へ', folder_path(@folder)