config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
     controllers: { sessions: 'user/sessions' }

  devise_scope :user do
    authenticated :user do
      # 認証済みユーザーの場合はファイル一覧へ
      root to: 'folders#show'
    end
    unauthenticated :user do
      root to: 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  # folder_idはどのフォルダ一覧へ戻るかを示すためのキー。省略可能。省略時はrootへ戻る事になる
  get 'find(/:folder_id)' => 'find#new', as: 'find', defaults: {folder_id: nil}
  post 'find(/:folder_id)' => 'find#show', as: 'find_result', defaults: {folder_id: nil}

  resources :folders, only: [:show] do
    member do
      # /folders/3/search | /search/3
      get :search
    end
    resources :upfiles, only: [:edit, :create, :new, :destroy, :update, :show] do
      member do
        get :download
        post :move, :copy
        resource :fileshare, only: [:new, :update, :destroy]
        namespace 'toshare' do
          get :show, to: 'upfiles#show'
          get :download, to: 'upfiles#download'
        end
      end
    end

    resources :folders, controller: :subfolders, only: [:edit, :create, :new, :destroy, :update, :show] do
      member do
        post :move, :copy
        resource :foldershare, only: [:new, :update, :destroy]
        namespace 'toshare' do
          get :show, to: 'subfolders#show'
        end
      end
    end
  end

  namespace 'fromshare' do
    resources :items, only: [:index]
  end

  namespace 'toshare' do
    resources :items, only: [:index]
    resources :folders, only: [:show]
  end

  resources :events, only: [:index]
end

app/controllers/subfolders_controller.rb
class SubfoldersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_parent_folder
  before_action :set_folder, only: [:show, :edit, :update, :destroy, :move, :copy]

  def show
  end

  def edit
  end

  def new
    @folder = @parent_folder.sub_folders.build
  end

  def create
    rec_values = folder_params
    rec_values[:user_id] = current_user.id
    @folder = @parent_folder.sub_folders.build(rec_values)

    respond_to do |format|
      if @folder.save
        format.html { redirect_to folder_path(@parent_folder), notice: 'フォルダを作成しました' }
      else
        format.html { render :new }
      end
    end
  end

  def move
    respond_to do |format|
      if @folder.deepmove(folder_movecopy_params)
        format.html { redirect_to folder_path(folder_movecopy_params), notice: '移動しました' }
      else
        format.html { redirect_to folder_path(@parent_folder.id) , notice: @folder.errors.messages[:parent_folder_id].join }
      end
    end
  end

  def copy
    respond_to do |format|
      if @folder.deepcopy(folder_movecopy_params)
        format.html { redirect_to folder_path(folder_movecopy_params), notice: 'コピーしました' }
      else
        format.html { redirect_to folder_path(@parent_folder.id) , notice: @folder.errors.messages[:parent_folder_id].join }
      end
    end
  end

  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to folder_folder_path(@parent_folder, @folder), notice: 'フォルダ名を変更しました' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @folder.destroy
    redirect_to folder_path(@parent_folder), notice: 'フォルダを削除しました'
  end

  private
    def set_parent_folder
      @parent_folder = current_user.folders.find(params[:folder_id])
    end
    def set_folder
      @folder = @parent_folder.sub_folders.find(params[:id])
    end

    def folder_params
      params.require(:folder).permit(:name)
    end

    def folder_movecopy_params
      params.require(:to_folder_id)
    end
end

app/controllers/toshare/subfolders_controller.rb
class Toshare::SubfoldersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_folder, only: [:show]

  def show
  end

  private
    def set_folder
      @folder = current_user.to_share_folders.find(params[:id])
    end
end

app/views/subfolders/_form.html.haml
= form_for ([@parent_folder, @folder]) do |f|
  - if @folder.errors.any?
    #error_explanation
      %h2= "#{pluralize(@folder.errors.count, "error")} prohibited this folder from being saved:"
      %ul
        - @folder.errors.full_messages.each do |msg|
          %li= msg
  = f.text_field :name
  .actions
    = f.submit '保存'

app/views/subfolders/edit.html.haml
%h1 フォルダ名変更

= render 'form'

%hr
= link_to '戻る', :back

app/views/subfolders/new.html.haml
%h1 フォルダを作成する

= render 'form'

%hr
= link_to '戻る', folder_path(@parent_folder)

app/views/subfolders/shareedit.html.haml
%h1 フォルダ共有

= render 'form'

%hr
=link_to '戻る', :back

app/views/subfolders/show.html.haml
%p
  %strong フォルダ名:
  = @folder.name
%p
  %strong 更新日時:
  = get_disp_update_time(@folder)
%p
  %strong 所有者:
  = @folder.own_user.email
%p
  %strong 共有相手:
  = @folder.to_share_users.pluck(:email).uniq.join(', ')
%hr

- parent_folder = @folder.parent_folder
= link_to '編集', edit_folder_folder_path(parent_folder, @folder)
\|
= link_to '移動', '', id: "show_movetree"
\|
= link_to 'コピー', '', id: "show_copytree"
\|
= link_to '一覧へ', folder_path(@folder.parent_folder)


#movetreedialog
  = render 'folders/searchform', { param: { title: '移動', form_for: [parent_folder, @folder], url: move_folder_folder_path(parent_folder, @folder) } }

#copytreedialog
  = render 'folders/searchform', { param: { title: 'コピー', form_for: [parent_folder, @folder], url: copy_folder_folder_path(parent_folder, @folder) } }